version: "3.3"
services:
  business_app:
    container_name: sultr-business-app
    build:
      context: ./business-app
      dockerfile: dev.Dockerfile
    volumes:
      - ./business-app:/app
      - /app/node_modules
    image: sultr-business-app:1.0.0
    ports:
      - 4000:4000
    restart: on-failure

  api:
    container_name: sultr-api
    env_file: ./api/dev.env
    build:
      context: ./api
      dockerfile: dev.Dockerfile
      args:
        app_env: ${APP_ENV:-development}
    volumes:
      - ./api:/api
    image: sultr-api:1.0.0
    ports:
      - 4001:8080
    restart: on-failure

  mongo:
    container_name: sultr-mongo
    build:
      context: ./mongo
      dockerfile: dev.Dockerfile
    volumes:
      - ./mongo/db:/data/db
    image: sultr-mongo:1.0.0
    hostname: sultr-mongo
    ports:
      - 4002:27017
    restart: on-failure
