steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', "$_IMAGE", './api']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', "$_IMAGE"]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'sultr-api', '--image', "$_IMAGE", '--region', "europe-west-1"]
images:
  - "$_IMAGE"
substitutions:
  _IMAGE: "gcr.io/${PROJECT_ID}/sultr-api-${SHORT_SHA}"
